### ISSUE TITLE
FFmpeg not installed for Mac with Blender 4.3.0

### ISSUE THREAD

**Issue by mac4kent** [dshot92/render-multiple-instances#1]
There not work for me on FFmpeg not install
Blender.app on 4.3.0 Beta of October 3, 2024
![image](https://github.com/user-attachments/assets/ba539a81-efea-46ad-b0d1-9e8001c474af)

![image](https://github.com/user-attachments/assets/0c60a2bb-eb41-441e-bb7c-ca42da70a0e4)

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	Mac15,7
  Model Number:	MRW43LL/A
  Chip:	Apple M3 Pro
  Total Number of Cores:	12 (6 performance and 6 efficiency)
  Memory:	18 GB
  System Firmware Version:	11881.1.1
  OS Loader Version:	11881.1.1
  Serial Number (system):	HPW7VKG2D9
  Hardware UUID:	30E70298-022A-511D-A2F9-EF855835F739
  Provisioning UDID:	00006030-001A051102D9001C
  Activation Lock Status:	Disabled

---

Apple M3 Pro:

  Chipset Model:	Apple M3 Pro
  Type:	GPU
  Bus:	Built-In
  Total Number of Cores:	18
  Vendor:	Apple (0x106b)
  Metal Support:	Metal 3
  Displays:
Color LCD:
  Display Type:	Built-in Liquid Retina XDR Display
  Resolution:	3456 x 2234 Retina
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal

**Comment by dshot92** [comment]
Do you have `ffmpeg` installed on you machine?
Seems like it is not.

Try running `ffmpeg` command in a terminal.
If it is installed it should output text, starting with the version.

If it does, it is installed.

If not, install it. You can check on Google but an easy way would be to run

```sh
brew update
brew upgrade
brew install ffmpeg
```

Restart Blender and it should work fine.

**Comment by mac4kent** [comment]
![image](https://github.com/user-attachments/assets/019e110d-75e7-4702-8ed9-4950d053a662)

**Comment by mac4kent** [comment]
MacOS 15.0

**Comment by dshot92** [comment]
You are missing the [Brew](https://brew.sh/) package manager.

Install it with this command:
```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```


The run the command to install ffmpeg:
```sh
brew install ffmpeg
```

Also, I just noticed that your output settings are set to mp4. You should use jpg or png, as ffmpeg will use image sequence to create the final video.

**Comment by mac4kent** [comment]
![image](https://github.com/user-attachments/assets/0a54d13b-75ad-4922-bc41-d4eda099fab4)

and ok let me copy from your text above.

**Comment by dshot92** [comment]
You are looking in the wrong dropdown. 

Just a few lines above, change `FFmpeg video` to `PNG`.
It should be fine.

**Comment by mac4kent** [comment]
Ok I just did change to be PNG still not install.

**Comment by mac4kent** [comment]
![image](https://github.com/user-attachments/assets/4911797a-be04-4c52-9cd6-10f3aafd08bd)

**Comment by mac4kent** [comment]
![image](https://github.com/user-attachments/assets/63f68a01-ba38-404e-b9d5-9df5b0dc2a80)

**Comment by dshot92** [comment]
> ![image](https://github.com/user-attachments/assets/4911797a-be04-4c52-9cd6-10f3aafd08bd)
> 
Did you run the command in the last section `next steps`?

That would allow brew to be run from the any terminal windows easily.

**Comment by mac4kent** [comment]
I don't know. 
for Mac only is cd /Volumes/
That is not C:/>

**Comment by dshot92** [comment]
Run these three command:
![373476626-4911797a-be04-4c52-9cd6-10f3aafd08bd~2.png](https://github.com/user-attachments/assets/e946e4c3-c3d4-4fb5-b385-d9eb04a43751)

**Comment by mac4kent** [comment]
Oh I see. I just did copy each 3 list and finally.

Would you like to add and tutor how to step by step?

**Comment by mac4kent** [comment]
I just did "brew install ffmpeg" install complete and blender still not work "FFmpeg not install"

**Comment by mac4kent** [comment]
I am wait.

**Comment by dshot92** [comment]
> I am wait.

Just restart all, laptop and blender.

This should work.

**Comment by mac4kent** [comment]
I already restart and shutdown my MacBook Pro M3 Pro still not work for me ""FFmpeg not installed"

**Comment by dshot92** [comment]
What do you get when you run ffmpeg command in the terminal?

**Comment by mac4kent** [comment]
Terminal.app and type "ffmpeg" is information.
![image](https://github.com/user-attachments/assets/79649afb-796e-4a5c-b8cb-5a2b0ade5fe8)

**Comment by dshot92** [comment]
Try removing the extension and reinstalling it, but at this point i dont think its a problem with the code, more likely something is miscofigured in the laptop.

**Comment by mac4kent** [comment]
This is not LAPTOP.
LAPTOP = Windows only.
Macintosh is iMac, MacBook Air, MacBook Pro, and etc.

Do you have your own Macintosh computer?

**Comment by dshot92** [comment]
> This is not LAPTOP. LAPTOP = Windows only. Macintosh is iMac, MacBook Air, MacBook Pro, and etc.
> 
> Do you have your own Macintosh computer?

[Laptop](https://www.merriam-webster.com/dictionary/laptop)

**Comment by mac4kent** [comment]
Ok I am tell you know. There PATH is big different.

Path is Macintosh
cd /Volumes/

Path is Windows and DOS
cd c:/>

**Comment by mac4kent** [comment]
I just put screen record on my mac to show you on my youtube.
https://youtu.be/W-YNZFzUjXI

[Open blender 4.3.0.txt](https://github.com/user-attachments/files/17262204/Open.blender.4.3.0.txt)
.txt is from terminal list during open file through "Show Package Content" above.

**Comment by mac4kent** [comment]
My friend and Steve Job said MacBook, iBook, MacBook Air, MacBook Pro. That is NOT LAPTOP.
Windows, Linux is call Laptop only.
Laptop did not said (Macintosh) not there.

**Comment by dshot92** [comment]
Extension works as intended.

User didn't create a blender file, nothing to render.

Save blend file all works like exptected.

Closing
