### ISSUE TITLE
Locked

### ISSUE THREAD

**Issue by mac4kent** [dshot92/render-multiple-instances#2]
Why you put locked too fast without let me know.

I don't understand below
Extension works as intended.

User didn't create a blender file, nothing to render.

Save blend file all works like exptected.

Closing
What is intended, What is exptected?

**Comment by mac4kent** [comment]
![image](https://github.com/user-attachments/assets/c53f1e29-2d3d-4772-9d6c-72d1b302134e)
![image](https://github.com/user-attachments/assets/807b8779-ca0d-45bc-bf69-9a54c61a7a4f)

**Comment by dshot92** [comment]
Share blend file here

**Comment by mac4kent** [comment]
yes
https://mega.nz/file/A4VhiBxS#O2OS9Zz69QeyexWCDZlVXPbrv0tzhDs4LY7TF4xUqmc
Use file this "Holy Spirit SuperNatural 3.0.4.blend"

**Comment by mac4kent** [comment]
October 13, 2024 at 6:46 PM Mountain Time USA

https://youtu.be/g_iSn4x2KWg
[Render multiple Instances October 13, 2024 bug.txt](https://github.com/user-attachments/files/17357846/Render.multiple.Instances.October.13.2024.bug.txt)

**Comment by mac4kent** [comment]
I just found out why there path mistake.
Should put //../Flipbook/
See Output there wrong.
![image](https://github.com/user-attachments/assets/ea1d31bc-023c-4f2e-b603-ccd294104f87)

I rename and stubborn back too many.

Terminal said.
Last login: Sun Oct 13 19:19:48 on ttys000
kentdavis@Mac ~ % cd /Users/kentdavis/Documents/HSSuperNatural ASL/1 HSSuperNatural ASL 3.4.1/1 Blender/../Flipbook/1.0.1/flipbook_render_v001/
cd: too many arguments
kentdavis@Mac ~ % 

Make sure PATH correct for Mac.
Use "//../Flipbook/" is simply.

Better this below picture
![image](https://github.com/user-attachments/assets/5de2c065-499b-4889-92d5-1ba62a9b8c6b)

**Comment by dshot92** [comment]
I do not see the //../flipbook/ in those files.

I did push an update yesterday that allows to set the flipbook path and handles correctly the `//../dir/` paths.

To be clear, blender uses `//` as relative to the blend file.
Using `//../` would mean the parent folder from outside the locaiton of the blend file.

Glad the update fixed your issue thogh

**Comment by mac4kent** [comment]
Please do not put close. Stay open until fix it first.
You did not understand I am try tell you. There still error path for Macintosh.
That is not "//./Render Output/" only "//../Render Output/"
![Wrong path Blender 4 3 0 October 14, 2024](https://github.com/user-attachments/assets/cb9f0368-0f98-41da-b389-e5e3ecb28b45)

**Comment by mac4kent** [comment]
![image](https://github.com/user-attachments/assets/52efabcd-eb61-4a61-87f8-e7bfbe9e2936)
![image](https://github.com/user-attachments/assets/73e0a326-eb9c-47e0-87d6-7953dbe22850)

**Comment by dshot92** [comment]
In my previus message i actually meant `//../paths`, just a typo from mobile.

You seem to have the blender output path set with `flipbooks` in it.
You dont need to do that.
Set the flipbook path in the settings below, check auto encode flipbook and launch it.

`//` is used in blender to refer that the path is a relative to the blend file.
More info [here](https://docs.blender.org/manual/en/latest/editors/preferences/file_paths.html)

 About this:
 > Terminal said. Last login: Sun Oct 13 19:19:48 on ttys000 kentdavis@Mac ~ % cd /Users/kentdavis/Documents/HSSuperNatural ASL/1 HSSuperNatural ASL 3.4.1/1 Blender/../Flipbook/1.0.1/flipbook_render_v001/ cd: too many arguments kentdavis@Mac ~ %
 
Try removing spaces in the directory names.
If that is not it, I dont know what the problem is on your machine.


Here a test on my machine with both flipbook and normal render.

https://github.com/user-attachments/assets/9e37f58f-b6d9-4e19-bcd0-158c726c389a

https://github.com/user-attachments/assets/1d57ebfa-b9a5-4593-b3a5-b1a6ae242a51

**Comment by mac4kent** [comment]
Render Animation I did not click button.
Flipbook Viewport I did not do click Button.
Flipbook Render I already did make bug path.

Focus on (Flipbook Render) button

**Comment by mac4kent** [comment]
https://youtu.be/3G4pbcz7vuo

**Comment by mac4kent** [comment]
I already set few years ago.
![image](https://github.com/user-attachments/assets/5af4dd28-9054-4a4b-ad5b-f2170b47f173)
Only for Mac.

**Comment by dshot92** [comment]
Can you uninstall the extension from blender, 
Download this zip. (Is the same extension with new code for faster testing)

Drag the zip file over the blender windows and it will prompt to install it.

[render-multiple-instances.zip](https://github.com/user-attachments/files/17381917/render-multiple-instances.zip)

**Comment by mac4kent** [comment]
sure I did got download from your link.
Open normal Blender 4.3.0.app
Open my file.
Click (Flipbook Render) button
appear permission and I click see picture.
![Screenshot 2024-10-15 at 10 53 47 AM](https://github.com/user-attachments/assets/f029504c-64e2-4a04-99e6-5c81ccc8e434)

then

Terminal.app appear.
Last login: Tue Oct 15 10:53:50 on ttys001
open -a Terminal.app --args /Applications/Blender 4.3.0.app/Contents/MacOS/Blender -b /Users/kentdavis/Documents/HSSuperNatural ASL/1 HSSuperNatural ASL 3.4.1/1 Blender/Holy Spirit SuperNatural 3.0.4.blend -s 1 -e 3000 -a
kentdavis@Mac ~ % open -a Terminal.app --args /Applications/Blender 4.3.0.app/Contents/MacOS/Blender -b /Users/kentdavis/Documents/HSSuperNatural ASL/1 HSSuperNatural ASL 3.4.1/1 Blender/Holy Spirit SuperNatural 3.0.4.blend -s 1 -e 3000 -a
kentdavis@Mac ~ %

**Comment by dshot92** [comment]
Did the render worked out?

Are the frames there?

**Comment by mac4kent** [comment]
![image](https://github.com/user-attachments/assets/9b36d8b2-7e7d-4bbd-b437-d69fb9405421)
did not work (Flipbook Render) on Finder.

**Comment by dshot92** [comment]
Can you try with this?

[render-multiple-instances-v2.zip](https://github.com/user-attachments/files/17382210/render-multiple-instances-v2.zip)

**Comment by mac4kent** [comment]
Version 2 . zip
Still not work.
![image](https://github.com/user-attachments/assets/a46dc851-6025-49e2-80cc-36aee013a796)

Last login: Tue Oct 15 11:16:26 on ttys001
open -a Terminal.app --args '/Applications/Blender 4.3.0.app/Contents/MacOS/Blender' -b '/Users/kentdavis/Documents/HSSuperNatural ASL/1 HSSuperNatural ASL 3.4.1/1 Blender/Holy Spirit SuperNatural 3.0.4.blend' -s 1 -e 3000 -a
kentdavis@Mac ~ % open -a Terminal.app --args '/Applications/Blender 4.3.0.app/Contents/MacOS/Blender' -b '/Users/kentdavis/Documents/HSSuperNatural ASL/1 HSSuperNatural ASL 3.4.1/1 Blender/Holy Spirit SuperNatural 3.0.4.blend' -s 1 -e 3000 -a
kentdavis@Mac ~ %

**Comment by dshot92** [comment]
Do the termianl windows appear on screen?

Do they seem to render the frames?

Can you make a video?

**Comment by mac4kent** [comment]
yes

**Comment by mac4kent** [comment]
When click 1 time on (Flipbook Render) button cause Terminal appear 3 times itself.
https://youtu.be/LDlnegDHB7o

I will have to go food store then come back let you know.

**Comment by dshot92** [comment]
No problem.

[render-multiple-instances-v3.zip](https://github.com/user-attachments/files/17382494/render-multiple-instances-v3.zip)

**Comment by mac4kent** [comment]
Version 3
https://youtu.be/BLZ6cU-Lwps
You may notice this youtube that funny.
Output:
//../FlipbookNOW/1.0.0/

Render Multiple Instances:
//../FlipbookNOW/1.0.1/

![image](https://github.com/user-attachments/assets/e0ddf239-6744-448c-9acc-c781da653697)

**Comment by dshot92** [comment]
Did it encode?

**Comment by mac4kent** [comment]
Yes it work but make sure only one Terminal.app appear. Not 3 appear in same time.

**Comment by dshot92** [comment]
No, i want the termianl to appear, i does show me how many instances are being launched, and if there are problems.

**Comment by mac4kent** [comment]
Yes I agree with you I wants the terminal to appear of course but there double 3 (see picture) itself. Need to fix become only 1.

![image](https://github.com/user-attachments/assets/3aa12143-79f7-48c0-bfae-34e71418ed51)
![image](https://github.com/user-attachments/assets/80f3598b-c5aa-423c-b77c-f85823f6dd04)

**Comment by mac4kent** [comment]
Are you still work some more your code?

**Comment by dshot92** [comment]
Not for now. 

Thanks for testing!

I ypdated the extension of the blender platform.

**Comment by dshot92** [comment]
Not for now. 

Thanks for testing!

I updated the extension of the blender platform.

**Comment by mac4kent** [comment]
Allright no problem
When you are ready work on your code then I will help you my video record for you later.
I am very glad for you made it on code. I did check take me few hours and hours until I found you did great good job to put.

class OS(Enum):
    WINDOWS = "Windows"
    MACOS = "MacOS"
    LINUX = "Linux"
    UNKNOWN = "Unknown"
smile.
