### ISSUE TITLE
No such file or directory: 'x-terminal-emulator'

### ISSUE THREAD

**Issue by oluemm** [dshot92/render-multiple-instances#4]
![image](https://github.com/user-attachments/assets/3fc97366-9353-4be5-b970-1babdfd52b78)
I can't render animation on Blender v4.2(Flatpak) Ubuntu 24.04.

Keeps throwing this error.

**Comment by dshot92** [comment]
I've never used blender from flatpak.

Can it be messing with permission?

**Comment by oluemm** [comment]
Yeah, It is probably permissions issue. Works well with snap version
